// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kGJwQ8mtSPC7EXUCXqgo9DveVFB9Nis',
    appId: '1:775789560761:web:32058fb90b4d9981a72c68',
    messagingSenderId: '775789560761',
    projectId: 'melos-76768',
    authDomain: 'melos-76768.firebaseapp.com',
    storageBucket: 'melos-76768.firebasestorage.app',
    measurementId: 'G-PEBT4XBN5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBonMSg5qWfdKL_OMfrLwPQnSUlbm8idIg',
    appId: '1:775789560761:android:17dc106ece606dcfa72c68',
    messagingSenderId: '775789560761',
    projectId: 'melos-76768',
    storageBucket: 'melos-76768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULWmFibzBGdOpk9bvhN7ZzxaBtS-syUs',
    appId: '1:775789560761:ios:4fa3a21509154e6aa72c68',
    messagingSenderId: '775789560761',
    projectId: 'melos-76768',
    storageBucket: 'melos-76768.firebasestorage.app',
    iosBundleId: 'com.example.melos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCULWmFibzBGdOpk9bvhN7ZzxaBtS-syUs',
    appId: '1:775789560761:ios:4fa3a21509154e6aa72c68',
    messagingSenderId: '775789560761',
    projectId: 'melos-76768',
    storageBucket: 'melos-76768.firebasestorage.app',
    iosBundleId: 'com.example.melos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kGJwQ8mtSPC7EXUCXqgo9DveVFB9Nis',
    appId: '1:775789560761:web:27e8cfbbf9a32144a72c68',
    messagingSenderId: '775789560761',
    projectId: 'melos-76768',
    authDomain: 'melos-76768.firebaseapp.com',
    storageBucket: 'melos-76768.firebasestorage.app',
    measurementId: 'G-LYTYWNPWH6',
  );
}
